### ISSUE TITLE
📄 デフォルトYAMLレイアウトファイル作成

### ISSUE THREAD

**Issue by t-seki** [t-seki/key-overlay-fps#10]
## 🎯 目的
既存の65%キーボードとFPSキーボードレイアウトをYAMLファイルとして作成

### 1. 65%キーボードレイアウト (layouts/65_keyboard.yaml)
現在のMainWindow.xamlにハードコーディングされている65%キーボードレイアウトをYAML化

#### 対象キー (約60個)
- 数字キー: 1-0
- 英字キー: Q-P, A-L, Z-M
- 機能キー: Esc, Tab, Shift, Ctrl, Alt, Space等
- 記号キー: -, =, [, ], ;, ', `, \, ,, ., /

#### マウス要素
- マウス本体、左右ボタン、ホイールボタン
- サイドボタン（4, 5）
- スクロール表示（上下）
- 32方向移動可視化

### 2. FPSキーボードレイアウト (layouts/fps_keyboard.yaml)
FPSゲーム特化レイアウト

#### 対象キー (約20個)
- 移動キー: W, A, S, D
- アクションキー: Space, Shift, Ctrl, R, F, E
- 数字キー: 1-5
- 機能キー: Tab, Esc

### 基本構造
```yaml
profile:
  name: "65%キーボード"
  description: "一般的な65%キーボードレイアウト"
  version: "1.0"

window:
  width: 580
  height: 160

keys:
  - name: "KeyEscape"
    position: { x: 5, y: 5 }
    size: { width: 26, height: 26 }
    text: "Esc"
    virtualKey: 27
    borderStyle:
      color: "White"
      thickness: 1
      cornerRadius: 2
    fontStyle:
      size: 8
      weight: "Bold"
      color: "White"

mouse:
  enabled: true
  position: { x: 480, y: 20 }
  body:
    size: { width: 60, height: 90 }
  buttons:
    - name: "MouseLeft"
      offset: { x: 3, y: 3 }
      size: { width: 28, height: 15 }
    - name: "MouseRight"
      offset: { x: 32, y: 3 }
      size: { width: 28, height: 15 }
  # ... 他のマウス要素
```

### 1. MainWindow.xaml解析
- [ ] 既存のBorder要素座標を抽出
- [ ] Canvas.Left, Canvas.Top値の収集
- [ ] Width, Height値の収集
- [ ] TextBlock内容の抽出

### 2. YAML構造への変換
- [ ] 各キー要素をKeyDefinition形式に変換
- [ ] マウス要素をMouseDefinition形式に変換
- [ ] スタイル情報の抽出と構造化

### 3. データ検証
- [ ] 座標値の正確性確認
- [ ] キー数の整合性確認
- [ ] VirtualKey値の正確性確認

## 🧪 検証項目
- [ ] YAML構文の正確性
- [ ] 生成されるUIの視覚的整合性
- [ ] キー入力の動作確認
- [ ] マウス操作の動作確認
- [ ] レイアウト切り替えの動作確認

## ✅ 受け入れ条件
- [ ] 65%キーボードYAMLファイルの完成
- [ ] FPSキーボードYAMLファイルの完成
- [ ] 既存のXAMLレイアウトと視覚的に同等
- [ ] 全キーの動作確認完了
- [ ] YAML構文検証ツールでのチェック通過

## 🔗 依存関係
- Issue #8: 動的UI生成エンジン実装 (前提)
- Epic: Issue #6

## 📦 成果物
- `layouts/65_keyboard.yaml`
- `layouts/fps_keyboard.yaml`
- YAMLスキーマ定義ファイル（オプション）
