### ISSUE TITLE
🎯 [Epic] YAML動的レイアウト + プロファイル管理システム実装

### ISSUE THREAD

**Issue by t-seki** [t-seki/key-overlay-fps#6]
## 🎯 概要
XAMLに依存しないYAMLベースの動的レイアウトシステムとプロファイル管理機能の実装

## 📋 背景・経緯
Issue#2の統一設定システム実装において循環参照問題（StackOverflowException）が発生しました。より実用的で段階的なアプローチとして、以下の方針に転換します：

1. **安定した旧設定システムをベースに維持** (commit: f332760で完了)
2. **XAMLからYAMLファイルへの動的レイアウト生成**
3. **ユーザーフレンドリーなプロファイル管理**

## 🚀 実装戦略の利点
- ✅ **即座の安定性**: 動作する旧設定システムベース
- ✅ **高い柔軟性**: XAMLに依存しない動的UI生成
- ✅ **ユーザビリティ向上**: YAMLで簡単にレイアウトカスタマイズ可能
- ✅ **段階的実装**: 各機能を独立して開発・テスト可能
- ✅ **将来の拡張性**: 新しいキーボード形式やゲーム向けレイアウトを簡単追加

### ✅ フェーズ1: 安定基盤の確保 (完了)
- [x] MainWindowコンストラクタを旧設定システムベースに復元 
- [x] 基本的な動作確認とテスト
- [x] コミット: f332760 - 安定動作確認済み

### 🔄 フェーズ2: YAML動的レイアウトシステム設計
- [ ] LayoutDefinitionクラス設計（YAML構造体）
- [ ] UIGeneratorクラス設計（Canvas動的生成）
- [ ] KeyEventBinderクラス設計（イベント自動バインディング）
- [ ] YAML構造の定義と検証

### 🔧 フェーズ3: 動的UI生成エンジン実装
- [ ] YAMLパーサーとUI生成クラス実装
- [ ] Canvas要素の動的作成
- [ ] イベントハンドリングの自動バインディング
- [ ] 65%キーボード・FPSキーボード用YAMLファイル作成

### ⚙️ フェーズ4: プロファイル管理機能
- [ ] ProfileManagerクラス実装
- [ ] プロファイル保存/読み込み機能
- [ ] 実行時プロファイル切り替え
- [ ] カスタムプロファイル作成UI

### YAML構造例
```yaml
# layouts/65_keyboard.yaml
profile:
  name: "65%キーボード"
  window:
    width: 580
    height: 160
  
keys:
  - name: "KeyEscape"
    position: { x: 5, y: 5 }
    size: { width: 26, height: 26 }
    text: "Esc"
    virtualKey: 27
    
mouse:
  enabled: true
  position: { x: 480, y: 20 }
  buttons:
    - name: "MouseLeft"
      offset: { x: 3, y: 3 }
      size: { width: 28, height: 15 }
```

### 新しいクラス構成
```csharp
public class LayoutDefinition    // YAML構造体
public class UIGenerator         // Canvas動的生成
public class ProfileManager      // プロファイル管理
public class KeyEventBinder      // イベント自動バインディング
```

## 🎯 期待される成果
- **XAMLに依存しない柔軟なレイアウト管理**
- **ユーザーが簡単にカスタマイズ可能**
- **新しいキーボード形式の簡単な追加**
- **安定した動作とメンテナンス性の向上**
- **Issue#2の本質的な目標（保守性・拡張性向上）の実現**

## 🔗 関連Issue
- Issue #2: 設定管理の統一化（本Epicで実用的なアプローチで解決）
- 今後作成予定のサブIssue

## 📈 成功指標
1. YAMLファイルから完全にUIが生成される
2. ユーザーがYAMLを編集してレイアウトを変更可能
3. プロファイルの保存・読み込み・切り替えが正常動作
4. 既存機能の互換性維持
5. パフォーマンスの劣化なし
