### ISSUE TITLE
🎨 YAML動的レイアウトシステム設計

### ISSUE THREAD

**Issue by t-seki** [t-seki/key-overlay-fps#7]
## 🎯 目的
XAMLベースのハードコーディングされたレイアウトを、YAMLファイルから動的に生成するシステムの設計

### 1. LayoutDefinitionクラス設計
```csharp
public class LayoutDefinition
{
    public ProfileInfo Profile { get; set; }
    public List<KeyDefinition> Keys { get; set; }
    public MouseDefinition Mouse { get; set; }
    public WindowDefinition Window { get; set; }
}

public class KeyDefinition
{
    public string Name { get; set; }
    public Position Position { get; set; }
    public Size Size { get; set; }
    public string Text { get; set; }
    public string ShiftText { get; set; }
    public int VirtualKey { get; set; }
    public bool IsVisible { get; set; } = true;
}
```

### 2. YAML構造定義
```yaml
# layouts/65_keyboard.yaml
profile:
  name: "65%キーボード"
  description: "一般的な65%キーボードレイアウト"
  
window:
  width: 580
  height: 160
  
keys:
  - name: "KeyEscape"
    position: { x: 5, y: 5 }
    size: { width: 26, height: 26 }
    text: "Esc"
    virtualKey: 27
    visible: true
    
  - name: "Key1"
    position: { x: 33, y: 5 }
    size: { width: 26, height: 26 }
    text: "1"
    shiftText: "\!"
    virtualKey: 49
    visible: true

mouse:
  enabled: true
  position: { x: 480, y: 20 }
  buttons:
    - name: "MouseLeft"
      offset: { x: 3, y: 3 }
      size: { width: 28, height: 15 }
    - name: "MouseRight"
      offset: { x: 32, y: 3 }
      size: { width: 28, height: 15 }
```

### 3. UIGeneratorクラス設計
```csharp
public class UIGenerator
{
    public Canvas GenerateLayoutFromYaml(string yamlPath);
    private Border CreateKeyElement(KeyDefinition keyDef);
    private Canvas CreateMouseElements(MouseDefinition mouseDef);
    private void BindEventHandlers(FrameworkElement element, string elementName);
}
```

### 4. KeyEventBinderクラス設計
```csharp
public class KeyEventBinder
{
    public void BindKeyEvents(Border keyElement, int virtualKey);
    public void BindMouseEvents(Border mouseElement, int buttonId);
    private void RegisterKeyboardInputHandler(FrameworkElement element);
}
```

## ✅ 受け入れ条件
- [ ] LayoutDefinitionクラスの完成
- [ ] YAML構造の仕様策定
- [ ] UIGeneratorクラスの設計完了
- [ ] KeyEventBinderクラスの設計完了
- [ ] 設計ドキュメントの作成

## 🔗 Epic
Issue #6: YAML動的レイアウト + プロファイル管理システム実装

## 📦 次のステップ
完了後 → Issue: 動的UI生成エンジン実装
